<?php
/**
 * @file Provides flag support for search api
 */

use Drupal\flag_search_api\Utility\FlagSearchApiHelper;

/**
 * Implements hook_entity_insert().
 */
function flag_search_api_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  FlagSearchApiHelper::reindexItem($entity);
}

/**
 * Implements hook_entity_update().
 */
function flag_search_api_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  FlagSearchApiHelper::reindexItem($entity);
}

/**
 * Implements hook_entity_delete().
 */
function flag_search_api_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  FlagSearchApiHelper::reindexItem($entity);
}

